[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.4"
substring = "1.4.5"
lazy_static = "1.5.0"
regex = "1.12.2"
memoize = "0.5.1"
itertools = "0.14.0"
